// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpvfktvutyaymdrmvyqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwdmZrdHZ1dHlheW1kcm12eXF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MzgyNjIsImV4cCI6MjA2MzUxNDI2Mn0.lpPhkCpLf22wb2LcD0w5DAXhN54mYXc5BCi4PZVQSfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);